### ISSUE TITLE
Query parameters aren't combined in the links

### ISSUE THREAD

**Issue by ZJaume** [Helsinki-NLP/OPUS-MT-dashboard#1]
For example, querying results for zho-eng, then click in newstest2021 and the results in the page are correct, zho-eng newstest2021 scores, but the url only says `https://opus.nlpl.eu/leaderboard/index.php?test=newstest2021`. The same happens if, after clicking newstest2021, I click comet score for example. To quickly share this with anyone, the url should have all, or at least all non-null, parameters I've been filtering with. Maybe there's a way to format the href attributes so they only add a certain filter to the current query? Or instead of that, generate all hrefs with the full query?

**Comment by jorgtied** [comment]
I added an option in the header called [share link] that would give you a sharable link with all the options in the URI.

**Comment by ZJaume** [comment]
Nice! Much easier to share now.
